tegra-flashtools: integrate l4t_flash_prerequisites.sh into deploy image
Issue: LIN1025-5840

If user install all-new Ubuntu OS, and then deploy WRLinux onto Orin
AGX board directly, there is below error reported:
FileNotFoundError: [Errno 2] No such file or directory: 'dtc'
In order to fix this issue, integrate l4t_flash_prerequisites.sh into
deploy image, so that install necessary packages before deploying
WRLinux onto Orin AGX board.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Meng Li <Meng.Li@windriver.com>