cuda-samples: copy necessary configuration file to data directory
Issue: LIN1025-5571

When running cuda samples, e.g. simpleSurfaceWrite, there is below
error reported:
error: sdkFindFilePath: file <teapot512.pgm> not found!
So, add necessary configuration file to data directory so that run
cuda samples smoothly.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Meng Li <Meng.Li@windriver.com>